[package]
name = "cfddns"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15"
env_logger = "0.11.8"
log = "0.4.29"
reqwest = {version = "0.12", features=["blocking", "json"]}
serde = "1.0.228"
serde_json = {version = "1.0.145", features = ["derive"]}
